### ISSUE TITLE
Add "force encrypton" to config

### ISSUE THREAD

**Issue by gigerIT** [tzsk/crypton#88]
Hi,
I would like to have the option to only accept and return encrypted requests on my API.
Now if a request does not have the "X-RESPONSE-ENCRYPTED" header the response is in plain text.
My approach would be to add an option for forcing it to the config file.

**Comment by tzsk** [comment]
@gigerIT Add/Create your own custom Middleware and Set whatever additional headers you want.

Make sure you apply the middleware before the `Crypton` middleware in the Chain.
